version: '3'
services:
  app:
    build: .
    image: vdi:xfce

    environment:
    - PASSWORD=password
    - USER=user
    - KEYMAP="de"

    cap_add:
    - SYS_PTRACE
    stdin_open: true
    tty: true

    ports:
    - 4001:4000/tcp
    - 4443:4443/tcp
#    - 4080:4080/tcp

    # volumes:
    # - ./configs/server.cfg:/usr/NX/etc/server.cfg
    # - ./configs/node.cfg:/usr/NX/etc/node.cfg
    # - ./configs/bash_profile:/home/user/.bash_profile   # for keyboard layout
    # - ./configs/xfce4:/home/user/.config/xfce4          # XFCE4 config; setup for Desktop Look&Feel
    # - ./volumes/home:/home
    # networks:
    #   - backend

    labels:
      - "traefik.docker.network=backend"
      - "traefik.domain=vdi.dtpnk.tech"
      - "traefik.frontend.rule=Host:vdi.dtpnk.tech"
      - "traefik.enable=true"
      - "traefik.port=4080"
      # - "traefik.frontend.passHostHeader=true"
      # - "traefik.frontend.whiteList.useXForwardedFor=true"

# networks:
#   backend:
#     external: true
